name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn --prefer-offline --pure-lockfile --no-progress --non-interactive
      - name: Build
        run: yarn build
